// Bundles src/ into a single dependency-free dist/index.js. The output is committed:
// installing the plugin is a git clone with no build step, so dist/ must ship in the repo.
import { build } from "esbuild";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));

await build({
  absWorkingDir: root,
  entryPoints: ["src/index.ts"],
  outfile: "dist/index.js",
  bundle: true,
  platform: "node",
  target: "node20",
  format: "esm",
  banner: {
    js: [
      "// gemini-claude-bridge: GENERATED by scripts/build.mjs from src/. Do not edit by hand.",
      // Bundled CommonJS deps (cross-spawn, tree-kill) require() Node builtins; give the ESM bundle a real require.
      "import { createRequire as __bridgeCreateRequire } from 'node:module';",
      "const require = __bridgeCreateRequire(import.meta.url);",
    ].join("\n"),
  },
  define: { __BRIDGE_VERSION__: JSON.stringify(pkg.version) },
  legalComments: "eof",
  logLevel: "info",
});
