// Bundles src/ into dependency-free files under dist/. The output is committed: installing the
// plugin is a git clone with no build step, so dist/ must ship in the repo.
//   dist/index.js      MCP server (+ --check for the SessionStart banner)
//   dist/read-hook.js  PreToolUse hook for Read: runs before every Read, so it stays tiny
import { build } from "esbuild";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));

const common = {
  absWorkingDir: root,
  bundle: true,
  platform: "node",
  target: "node20",
  format: "esm",
  banner: {
    js: [
      "// gemini-claude-bridge: GENERATED by scripts/build.mjs from src/. Do not edit by hand.",
      // Bundled CommonJS deps (cross-spawn, tree-kill) require() Node builtins; give the ESM bundle a real require.
      "import { createRequire as __bridgeCreateRequire } from 'node:module';",
      "const require = __bridgeCreateRequire(import.meta.url);",
    ].join("\n"),
  },
  define: { __BRIDGE_VERSION__: JSON.stringify(pkg.version) },
  legalComments: "eof",
  logLevel: "info",
};

await build({ ...common, entryPoints: ["src/index.ts"], outfile: "dist/index.js" });
await build({ ...common, entryPoints: ["src/read-hook.ts"], outfile: "dist/read-hook.js" });
